Elevator project TTK4235: source/fsm.c File Reference
fsm.c File Reference
Implementation file for the finite state machine.
#include "fsm.h"
#include "elev.h"
#include "queue.h"
#include "timer.h"
#include <stdio.h>
Functions
void FSM_init ()
Initialize the FSM.
void FSM_event_button (elev_button_type_t button, int floor)
Trigger event because of button press: Add order to the queue and decide action to take based on current state.
void FSM_event_floor (int floor)
Trigger event when at a floor: Updates FSM_current_floor, set lights and decide action to take based on current state.
elev_motor_direction_t FSM_decide_direction ()
Calculates the desired direction of the motor depending on FSM_current_floor, FSM_desired_floor and q_direction_space.
void FSM_set_state (state s)
Change the state and update q_direction_space.
void FSM_stop_pressed_logic ()
Decision making when stop button is pressed.
void FSM_stop_depressed_logic ()
Decicion making when stop button is depressed. Decicion depends on if carriage is at a floor.
Detailed Description
Implementation file for the finite state machine.
Definition in file fsm.c.
Function Documentation
FSM_decide_direction()
elev_motor_direction_t FSM_decide_direction ()
Calculates the desired direction of the motor depending on FSM_current_floor, FSM_desired_floor and q_direction_space.
Returns
The desired motor direction
See also
References q_set_desired_floor()
Referenced by FSM_set_state(state s)
Definition at line 140 of file fsm.c.
FSM_event_button()
void FSM_event_button (elev_button_type_t button, int floor)
Trigger event because of button press: Add order to the queue and decide action to take based on current state.
As stated in FSM_set_state(state s), q_direction_space is set manually when in emergency stopped condition.
Parameters
[in] button The type of button that is pressed
[in] floor The floor which the button is pressed
See also
References q_set_desired_floor(), q_set_orders(elev_button_type_t button, int floor) (Queue), FSM_set_state(state s)
Referenced by main()
Definition at line 24 of file fsm.c.
FSM_event_floor()
void FSM_event_floor (int floor)
Trigger event when at a floor: Updates FSM_current_floor, set lights and decide action to take based on current state.
Parameters
[in] floor The floor which the elevator has arrived on
See also
References elev_set_floor_indicator(int floor), elev_set_motor_direction(elev_motor_direction_t dirn), elev_set_door_open_lamp(int value) (Hardware), timer_isTimeOut() (Timer) and FSM_set_state(state s)
Referenced by main()
Definition at line 84 of file fsm.c.
FSM_init()
void FSM_init ()
Initialize the FSM.
Set FSM_current_state to st_init, q_direction_space to DIRN_STOP, motor direction up and remove all orders.
Postcondition
The elevator will immediately observe if already at a floor, thus triggering further events. Therefore safe to set motor direction regardless of elevator positioning.
See also
References elev_set_motor_direction(elev_motor_direction_t dirn) and q_reset_orders()
Referenced by main()
Definition at line 14 of file fsm.c.
FSM_set_state()
void FSM_set_state (state s)
Change the state and update q_direction_space.
Set the necessary control values and execute the neccassary functions such that the elevator changes state. Update FSM_current_state and q_direction_space. However, q_direction_space is set manually when emergency stopped.
Parameters
[in] s The state which will be changed to
See also
References elev_set_motor_direction(elev_motor_direction_t dirn), elev_set_door_open_lamp(int value), elev_set_stop_lamp(int value) (Hardware),
q_set_direction_space(), q_remove_order(int floor), q_remove_order(int floor) (Queue), timer_start(), timer_isTimeOut() (Timer)
and FSM_decide_direction()
Referenced by FSM_init(), FSM_event_button(elev_button_type_t button, int floor), FSM_event_floor(int floor), FSM_stop_pressed_logic() and FSM_stop_depressed_logic()
Definition at line 160 of file fsm.c.
FSM_stop_depressed_logic()
void FSM_stop_depressed_logic ()
Decicion making when stop button is depressed. Decicion depends on if carriage is at a floor.
Change the state to st_stop_depressed, update FSM_stop_pressed and start the timer and turn of lamp if current state is st_stop_pressed.
See also
References timer_start(), elev_set_stop_lamp(int value) and FSM_set_state(state s)
Referenced by main()
Definition at line 226 of file fsm.c.
FSM_stop_pressed_logic()
void FSM_stop_pressed_logic ()
Decision making when stop button is pressed.
Update lamp if not FSM_stop_pressed. Change the state if the current state is not st_stop_pressed.
See also
References elev_set_stop_lamp(int value) and FSM_set_state(state s)
Referenced by main()
Definition at line 213 of file fsm.c.